modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="better_cave_encounters_world_tests"
version="1"
displayName="Better Cave Encounters World Tests"
description='''Manual real-catalogue qualification tests for Better Cave Encounters.'''

[[dependencies.better_cave_encounters_world_tests]]
modId="better_cave_encounters"
mandatory=true
versionRange="[0.2.0,)"
ordering="AFTER"
side="SERVER"

[[dependencies.better_cave_encounters_world_tests]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="SERVER"

[[dependencies.better_cave_encounters_world_tests]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="SERVER"
